{{- if eq .Values.flaggerApp.enable true -}}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "frontend-testab.fullname" . }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "frontend-testab.fullname" . }}
  service:
    port: {{ .Values.service.port }}
    targetPort: http
    gateways:
    - {{ .Values.gateway.name }}
    hosts:
    - {{ .Values.gateway.host.fqdn }}
    trafficPolicy:
      tls:
        mode: DISABLE
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: istio_request_duration_seconds_sum
        thresholdRange:
          max: 20
        interval: 1m
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.testab/
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://{{ include "frontend-testab.fullname" . }}-canary.testab:{{ .Values.service.port }}/"
{{- end -}}
