{{- if eq .Values.flaggerApp.enable false -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-testab.fullname" . }}
  labels:
{{- include "frontend-testab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http-web
  selector:
    {{- include "frontend-testab.selectorLabels" . | nindent 4 }}
{{- end -}}