{{- if eq .Values.flaggerApp.enable false -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "frontend-testab.fullname" . }}
spec:
  hosts:
  - {{ .Values.gateway.host.fqdn }}
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "frontend-testab.fullname" . }}
{{- end -}}
